name: "Portainer Stack Deploy Action"
description: "Deploy or Update a Portainer Stack from a Repository or Compose File"
author: "Shane"
branding:
  icon: "layers"
  color: "blue"

inputs:
  token:
    description: "Portainer Token"
    required: true
  url:
    description: "Portainer URL"
    required: true
  name:
    description: "Stack Name"
    required: true
  file:
    description: "Compose File"
    required: false
    default: "docker-compose.yaml"
  endpoint:
    description: "Portainer Endpoint ID"
    required: false
  ref:
    description: "Repository Ref"
    required: false
    default: "${{ github.ref }}"
  repo:
    description: "Repository URL"
    required: false
    default: "${{ github.server_url }}/${{ github.repository }}"
  tlsskip:
    description: "Skip TLS Repo Verification"
    required: false
    default: "false"
  prune:
    description: "Prune Services"
    required: false
    default: "true"
  pull:
    description: "Pull Images"
    required: false
    default: "true"
  type:
    description: "Deploy Type"
    required: false
    default: "repo"
  standalone:
    description: "Standalone Stack"
    required: false
    default: "false"
  env_json:
    description: "Dotenv JSON String"
    required: false
  env_file:
    description: "Dotenv File Path"
    required: false
  merge_env:
    description: "Merge Env Vars"
    required: false
    default: "false"
  username:
    description: "Repository Username"
    required: false
  password:
    description: "Repository Password"
    required: false
  fs_path:
    description: "Relative path volume in host (only available in Portainer BE)"
    required: false
  summary:
    description: "Add Summary to Job"
    required: false
    default: "true"

outputs:
  stackID:
    description: "Stack ID"
  swarmID:
    description: "Swarm ID"
  endpointID:
    description: "Endpoint ID"

runs:
  using: "node20"
  main: "dist/index.js"
