name: "Push"

on:
  workflow_dispatch:
  push:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Write YAML"
        id: yaml-action
        uses: teunmooij/yaml@v1
        with:
          data: '{"version":"3.8","services":{"alpine":{"image":"alpine","command":"tail -f /dev/null"}}}'
          to-file: "docker-compose.yaml"

      - name: "Test Local Action"
        id: test
        uses: ./
        with:
          token: ${{ secrets.PORTAINER_TOKEN }}
          url: ${{ secrets.PORTAINER_URL }}
          name: alpine-test
          file: docker-compose.yaml
          type: file
          env_json: '{"TEST": "TRUE"}'
          merge_env: true

      - name: "Echo Output"
        run: |
          echo stackID: '${{ steps.test.outputs.stackID }}'
          echo swarmID: '${{ steps.test.outputs.swarmID }}'
          echo endpointID: '${{ steps.test.outputs.endpointID }}'
